#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

require __DIR__ . '/common/config/env.php';
if ($yii_env['ENV'] == 'prod') {
	die("Can not run test in prod env.");
}

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
	require __DIR__ . '/common/config/main.php',
	require __DIR__ . "/common/config/main-{$yii_env['ENV']}.php",
	require __DIR__ . '/common/config/test.php',
	require __DIR__ . "/common/config/test-{$yii_env['ENV']}.php",
	require __DIR__ . '/console/config/main.php',
	require __DIR__ . "/console/config/main-{$yii_env['ENV']}.php",
	require __DIR__ . '/console/config/test.php',
	require __DIR__ . "/console/config/test-{$yii_env['ENV']}.php"
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
